on:
   workflow_dispatch:

jobs:
   example:
     runs-on: ubuntu-latest
     steps:
        - name: check if exists file
          run: |
           if [ -f config.yaml ]; then
           run : echo "::debug::config.yaml is exist"
            else 
            run : echo "::error::config.yaml is missed"
            fi
