name: first workflow

on:
   push: 
      branches:
         - main

jobs:
   jobs-example:
     runs-on: ubuntu-latest

     steps:
        - name: print welocome message
          run: echo "welcome to our first workflow"

        - name: checkout repo
          uses: actions/checkout@v6.0.2

        - name: List repo files
          run: ls -la
